
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package ve.edu.unet;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RPARENT = 7;
  public static final int POTENCIA = 11;
  public static final int SUMA = 8;
  public static final int MULTIPLICACION = 10;
  public static final int EOF = 0;
  public static final int NUMERO = 2;
  public static final int SIGNO = 5;
  public static final int IGUAL = 3;
  public static final int error = 1;
  public static final int DIVISION = 9;
  public static final int RESTA = 4;
  public static final int LPARENT = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMERO",
  "IGUAL",
  "RESTA",
  "SIGNO",
  "LPARENT",
  "RPARENT",
  "SUMA",
  "DIVISION",
  "MULTIPLICACION",
  "POTENCIA"
  };
}

